<?php
/**
 * AtaRegistroPreco
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AtaRegistroPreco Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AtaRegistroPreco implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AtaRegistroPreco';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'compra' => '\OpenAPI\Client\Model\Compra',
        'numero_ata_registro_preco' => 'string',
        'ano_ata' => 'int',
        'data_publicacao_pncp' => '\DateTime',
        'data_assinatura' => '\DateTime',
        'cancelado' => 'bool',
        'data_inclusao' => '\DateTime',
        'data_atualizacao' => '\DateTime',
        'data_vigencia_inicio' => '\DateTime',
        'data_vigencia_fim' => '\DateTime',
        'sequencial_ata' => 'int',
        'data_cancelamento' => '\DateTime',
        'excluido' => 'bool',
        'atributo_controle' => 'int',
        'numero_controle_pncp' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'compra' => null,
        'numero_ata_registro_preco' => null,
        'ano_ata' => 'int32',
        'data_publicacao_pncp' => 'date-time',
        'data_assinatura' => 'date',
        'cancelado' => null,
        'data_inclusao' => 'date-time',
        'data_atualizacao' => 'date-time',
        'data_vigencia_inicio' => 'date',
        'data_vigencia_fim' => 'date',
        'sequencial_ata' => 'int32',
        'data_cancelamento' => 'date-time',
        'excluido' => null,
        'atributo_controle' => 'int64',
        'numero_controle_pncp' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'compra' => false,
		'numero_ata_registro_preco' => false,
		'ano_ata' => false,
		'data_publicacao_pncp' => false,
		'data_assinatura' => false,
		'cancelado' => false,
		'data_inclusao' => false,
		'data_atualizacao' => false,
		'data_vigencia_inicio' => false,
		'data_vigencia_fim' => false,
		'sequencial_ata' => false,
		'data_cancelamento' => false,
		'excluido' => false,
		'atributo_controle' => false,
		'numero_controle_pncp' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'compra' => 'compra',
        'numero_ata_registro_preco' => 'numeroAtaRegistroPreco',
        'ano_ata' => 'anoAta',
        'data_publicacao_pncp' => 'dataPublicacaoPncp',
        'data_assinatura' => 'dataAssinatura',
        'cancelado' => 'cancelado',
        'data_inclusao' => 'dataInclusao',
        'data_atualizacao' => 'dataAtualizacao',
        'data_vigencia_inicio' => 'dataVigenciaInicio',
        'data_vigencia_fim' => 'dataVigenciaFim',
        'sequencial_ata' => 'sequencialAta',
        'data_cancelamento' => 'dataCancelamento',
        'excluido' => 'excluido',
        'atributo_controle' => 'atributoControle',
        'numero_controle_pncp' => 'numeroControlePNCP'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'compra' => 'setCompra',
        'numero_ata_registro_preco' => 'setNumeroAtaRegistroPreco',
        'ano_ata' => 'setAnoAta',
        'data_publicacao_pncp' => 'setDataPublicacaoPncp',
        'data_assinatura' => 'setDataAssinatura',
        'cancelado' => 'setCancelado',
        'data_inclusao' => 'setDataInclusao',
        'data_atualizacao' => 'setDataAtualizacao',
        'data_vigencia_inicio' => 'setDataVigenciaInicio',
        'data_vigencia_fim' => 'setDataVigenciaFim',
        'sequencial_ata' => 'setSequencialAta',
        'data_cancelamento' => 'setDataCancelamento',
        'excluido' => 'setExcluido',
        'atributo_controle' => 'setAtributoControle',
        'numero_controle_pncp' => 'setNumeroControlePncp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'compra' => 'getCompra',
        'numero_ata_registro_preco' => 'getNumeroAtaRegistroPreco',
        'ano_ata' => 'getAnoAta',
        'data_publicacao_pncp' => 'getDataPublicacaoPncp',
        'data_assinatura' => 'getDataAssinatura',
        'cancelado' => 'getCancelado',
        'data_inclusao' => 'getDataInclusao',
        'data_atualizacao' => 'getDataAtualizacao',
        'data_vigencia_inicio' => 'getDataVigenciaInicio',
        'data_vigencia_fim' => 'getDataVigenciaFim',
        'sequencial_ata' => 'getSequencialAta',
        'data_cancelamento' => 'getDataCancelamento',
        'excluido' => 'getExcluido',
        'atributo_controle' => 'getAtributoControle',
        'numero_controle_pncp' => 'getNumeroControlePncp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('compra', $data ?? [], null);
        $this->setIfExists('numero_ata_registro_preco', $data ?? [], null);
        $this->setIfExists('ano_ata', $data ?? [], null);
        $this->setIfExists('data_publicacao_pncp', $data ?? [], null);
        $this->setIfExists('data_assinatura', $data ?? [], null);
        $this->setIfExists('cancelado', $data ?? [], null);
        $this->setIfExists('data_inclusao', $data ?? [], null);
        $this->setIfExists('data_atualizacao', $data ?? [], null);
        $this->setIfExists('data_vigencia_inicio', $data ?? [], null);
        $this->setIfExists('data_vigencia_fim', $data ?? [], null);
        $this->setIfExists('sequencial_ata', $data ?? [], null);
        $this->setIfExists('data_cancelamento', $data ?? [], null);
        $this->setIfExists('excluido', $data ?? [], null);
        $this->setIfExists('atributo_controle', $data ?? [], null);
        $this->setIfExists('numero_controle_pncp', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['numero_ata_registro_preco'] === null) {
            $invalidProperties[] = "'numero_ata_registro_preco' can't be null";
        }
        if ($this->container['ano_ata'] === null) {
            $invalidProperties[] = "'ano_ata' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets compra
     *
     * @return \OpenAPI\Client\Model\Compra|null
     */
    public function getCompra()
    {
        return $this->container['compra'];
    }

    /**
     * Sets compra
     *
     * @param \OpenAPI\Client\Model\Compra|null $compra compra
     *
     * @return self
     */
    public function setCompra($compra)
    {
        if (is_null($compra)) {
            throw new \InvalidArgumentException('non-nullable compra cannot be null');
        }
        $this->container['compra'] = $compra;

        return $this;
    }

    /**
     * Gets numero_ata_registro_preco
     *
     * @return string
     */
    public function getNumeroAtaRegistroPreco()
    {
        return $this->container['numero_ata_registro_preco'];
    }

    /**
     * Sets numero_ata_registro_preco
     *
     * @param string $numero_ata_registro_preco numero_ata_registro_preco
     *
     * @return self
     */
    public function setNumeroAtaRegistroPreco($numero_ata_registro_preco)
    {
        if (is_null($numero_ata_registro_preco)) {
            throw new \InvalidArgumentException('non-nullable numero_ata_registro_preco cannot be null');
        }
        $this->container['numero_ata_registro_preco'] = $numero_ata_registro_preco;

        return $this;
    }

    /**
     * Gets ano_ata
     *
     * @return int
     */
    public function getAnoAta()
    {
        return $this->container['ano_ata'];
    }

    /**
     * Sets ano_ata
     *
     * @param int $ano_ata ano_ata
     *
     * @return self
     */
    public function setAnoAta($ano_ata)
    {
        if (is_null($ano_ata)) {
            throw new \InvalidArgumentException('non-nullable ano_ata cannot be null');
        }
        $this->container['ano_ata'] = $ano_ata;

        return $this;
    }

    /**
     * Gets data_publicacao_pncp
     *
     * @return \DateTime|null
     */
    public function getDataPublicacaoPncp()
    {
        return $this->container['data_publicacao_pncp'];
    }

    /**
     * Sets data_publicacao_pncp
     *
     * @param \DateTime|null $data_publicacao_pncp data_publicacao_pncp
     *
     * @return self
     */
    public function setDataPublicacaoPncp($data_publicacao_pncp)
    {
        if (is_null($data_publicacao_pncp)) {
            throw new \InvalidArgumentException('non-nullable data_publicacao_pncp cannot be null');
        }
        $this->container['data_publicacao_pncp'] = $data_publicacao_pncp;

        return $this;
    }

    /**
     * Gets data_assinatura
     *
     * @return \DateTime|null
     */
    public function getDataAssinatura()
    {
        return $this->container['data_assinatura'];
    }

    /**
     * Sets data_assinatura
     *
     * @param \DateTime|null $data_assinatura data_assinatura
     *
     * @return self
     */
    public function setDataAssinatura($data_assinatura)
    {
        if (is_null($data_assinatura)) {
            throw new \InvalidArgumentException('non-nullable data_assinatura cannot be null');
        }
        $this->container['data_assinatura'] = $data_assinatura;

        return $this;
    }

    /**
     * Gets cancelado
     *
     * @return bool|null
     */
    public function getCancelado()
    {
        return $this->container['cancelado'];
    }

    /**
     * Sets cancelado
     *
     * @param bool|null $cancelado cancelado
     *
     * @return self
     */
    public function setCancelado($cancelado)
    {
        if (is_null($cancelado)) {
            throw new \InvalidArgumentException('non-nullable cancelado cannot be null');
        }
        $this->container['cancelado'] = $cancelado;

        return $this;
    }

    /**
     * Gets data_inclusao
     *
     * @return \DateTime|null
     */
    public function getDataInclusao()
    {
        return $this->container['data_inclusao'];
    }

    /**
     * Sets data_inclusao
     *
     * @param \DateTime|null $data_inclusao data_inclusao
     *
     * @return self
     */
    public function setDataInclusao($data_inclusao)
    {
        if (is_null($data_inclusao)) {
            throw new \InvalidArgumentException('non-nullable data_inclusao cannot be null');
        }
        $this->container['data_inclusao'] = $data_inclusao;

        return $this;
    }

    /**
     * Gets data_atualizacao
     *
     * @return \DateTime|null
     */
    public function getDataAtualizacao()
    {
        return $this->container['data_atualizacao'];
    }

    /**
     * Sets data_atualizacao
     *
     * @param \DateTime|null $data_atualizacao data_atualizacao
     *
     * @return self
     */
    public function setDataAtualizacao($data_atualizacao)
    {
        if (is_null($data_atualizacao)) {
            throw new \InvalidArgumentException('non-nullable data_atualizacao cannot be null');
        }
        $this->container['data_atualizacao'] = $data_atualizacao;

        return $this;
    }

    /**
     * Gets data_vigencia_inicio
     *
     * @return \DateTime|null
     */
    public function getDataVigenciaInicio()
    {
        return $this->container['data_vigencia_inicio'];
    }

    /**
     * Sets data_vigencia_inicio
     *
     * @param \DateTime|null $data_vigencia_inicio data_vigencia_inicio
     *
     * @return self
     */
    public function setDataVigenciaInicio($data_vigencia_inicio)
    {
        if (is_null($data_vigencia_inicio)) {
            throw new \InvalidArgumentException('non-nullable data_vigencia_inicio cannot be null');
        }
        $this->container['data_vigencia_inicio'] = $data_vigencia_inicio;

        return $this;
    }

    /**
     * Gets data_vigencia_fim
     *
     * @return \DateTime|null
     */
    public function getDataVigenciaFim()
    {
        return $this->container['data_vigencia_fim'];
    }

    /**
     * Sets data_vigencia_fim
     *
     * @param \DateTime|null $data_vigencia_fim data_vigencia_fim
     *
     * @return self
     */
    public function setDataVigenciaFim($data_vigencia_fim)
    {
        if (is_null($data_vigencia_fim)) {
            throw new \InvalidArgumentException('non-nullable data_vigencia_fim cannot be null');
        }
        $this->container['data_vigencia_fim'] = $data_vigencia_fim;

        return $this;
    }

    /**
     * Gets sequencial_ata
     *
     * @return int|null
     */
    public function getSequencialAta()
    {
        return $this->container['sequencial_ata'];
    }

    /**
     * Sets sequencial_ata
     *
     * @param int|null $sequencial_ata sequencial_ata
     *
     * @return self
     */
    public function setSequencialAta($sequencial_ata)
    {
        if (is_null($sequencial_ata)) {
            throw new \InvalidArgumentException('non-nullable sequencial_ata cannot be null');
        }
        $this->container['sequencial_ata'] = $sequencial_ata;

        return $this;
    }

    /**
     * Gets data_cancelamento
     *
     * @return \DateTime|null
     */
    public function getDataCancelamento()
    {
        return $this->container['data_cancelamento'];
    }

    /**
     * Sets data_cancelamento
     *
     * @param \DateTime|null $data_cancelamento data_cancelamento
     *
     * @return self
     */
    public function setDataCancelamento($data_cancelamento)
    {
        if (is_null($data_cancelamento)) {
            throw new \InvalidArgumentException('non-nullable data_cancelamento cannot be null');
        }
        $this->container['data_cancelamento'] = $data_cancelamento;

        return $this;
    }

    /**
     * Gets excluido
     *
     * @return bool|null
     */
    public function getExcluido()
    {
        return $this->container['excluido'];
    }

    /**
     * Sets excluido
     *
     * @param bool|null $excluido excluido
     *
     * @return self
     */
    public function setExcluido($excluido)
    {
        if (is_null($excluido)) {
            throw new \InvalidArgumentException('non-nullable excluido cannot be null');
        }
        $this->container['excluido'] = $excluido;

        return $this;
    }

    /**
     * Gets atributo_controle
     *
     * @return int|null
     */
    public function getAtributoControle()
    {
        return $this->container['atributo_controle'];
    }

    /**
     * Sets atributo_controle
     *
     * @param int|null $atributo_controle atributo_controle
     *
     * @return self
     */
    public function setAtributoControle($atributo_controle)
    {
        if (is_null($atributo_controle)) {
            throw new \InvalidArgumentException('non-nullable atributo_controle cannot be null');
        }
        $this->container['atributo_controle'] = $atributo_controle;

        return $this;
    }

    /**
     * Gets numero_controle_pncp
     *
     * @return string|null
     */
    public function getNumeroControlePncp()
    {
        return $this->container['numero_controle_pncp'];
    }

    /**
     * Sets numero_controle_pncp
     *
     * @param string|null $numero_controle_pncp numero_controle_pncp
     *
     * @return self
     */
    public function setNumeroControlePncp($numero_controle_pncp)
    {
        if (is_null($numero_controle_pncp)) {
            throw new \InvalidArgumentException('non-nullable numero_controle_pncp cannot be null');
        }
        $this->container['numero_controle_pncp'] = $numero_controle_pncp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


