<?php
/**
 * AtaRegistroPrecoAlteracaoDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AtaRegistroPrecoAlteracaoDTO Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AtaRegistroPrecoAlteracaoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AtaRegistroPrecoAlteracaoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'numero_ata_registro_preco' => 'string',
        'ano_ata' => 'int',
        'data_assinatura' => '\DateTime',
        'data_vigencia_inicio' => '\DateTime',
        'data_vigencia_fim' => '\DateTime',
        'cancelado' => 'bool',
        'data_cancelamento' => '\DateTime',
        'justificativa' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'numero_ata_registro_preco' => null,
        'ano_ata' => 'int32',
        'data_assinatura' => 'date',
        'data_vigencia_inicio' => 'date',
        'data_vigencia_fim' => 'date',
        'cancelado' => null,
        'data_cancelamento' => 'date-time',
        'justificativa' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'numero_ata_registro_preco' => false,
		'ano_ata' => false,
		'data_assinatura' => false,
		'data_vigencia_inicio' => false,
		'data_vigencia_fim' => false,
		'cancelado' => false,
		'data_cancelamento' => false,
		'justificativa' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'numero_ata_registro_preco' => 'numeroAtaRegistroPreco',
        'ano_ata' => 'anoAta',
        'data_assinatura' => 'dataAssinatura',
        'data_vigencia_inicio' => 'dataVigenciaInicio',
        'data_vigencia_fim' => 'dataVigenciaFim',
        'cancelado' => 'cancelado',
        'data_cancelamento' => 'dataCancelamento',
        'justificativa' => 'justificativa'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'numero_ata_registro_preco' => 'setNumeroAtaRegistroPreco',
        'ano_ata' => 'setAnoAta',
        'data_assinatura' => 'setDataAssinatura',
        'data_vigencia_inicio' => 'setDataVigenciaInicio',
        'data_vigencia_fim' => 'setDataVigenciaFim',
        'cancelado' => 'setCancelado',
        'data_cancelamento' => 'setDataCancelamento',
        'justificativa' => 'setJustificativa'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'numero_ata_registro_preco' => 'getNumeroAtaRegistroPreco',
        'ano_ata' => 'getAnoAta',
        'data_assinatura' => 'getDataAssinatura',
        'data_vigencia_inicio' => 'getDataVigenciaInicio',
        'data_vigencia_fim' => 'getDataVigenciaFim',
        'cancelado' => 'getCancelado',
        'data_cancelamento' => 'getDataCancelamento',
        'justificativa' => 'getJustificativa'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('numero_ata_registro_preco', $data ?? [], null);
        $this->setIfExists('ano_ata', $data ?? [], null);
        $this->setIfExists('data_assinatura', $data ?? [], null);
        $this->setIfExists('data_vigencia_inicio', $data ?? [], null);
        $this->setIfExists('data_vigencia_fim', $data ?? [], null);
        $this->setIfExists('cancelado', $data ?? [], null);
        $this->setIfExists('data_cancelamento', $data ?? [], null);
        $this->setIfExists('justificativa', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['numero_ata_registro_preco'] === null) {
            $invalidProperties[] = "'numero_ata_registro_preco' can't be null";
        }
        if ($this->container['ano_ata'] === null) {
            $invalidProperties[] = "'ano_ata' can't be null";
        }
        if ($this->container['data_assinatura'] === null) {
            $invalidProperties[] = "'data_assinatura' can't be null";
        }
        if ($this->container['data_vigencia_inicio'] === null) {
            $invalidProperties[] = "'data_vigencia_inicio' can't be null";
        }
        if ($this->container['data_vigencia_fim'] === null) {
            $invalidProperties[] = "'data_vigencia_fim' can't be null";
        }
        if ($this->container['cancelado'] === null) {
            $invalidProperties[] = "'cancelado' can't be null";
        }
        if ($this->container['justificativa'] === null) {
            $invalidProperties[] = "'justificativa' can't be null";
        }
        if ((mb_strlen($this->container['justificativa']) > 2048)) {
            $invalidProperties[] = "invalid value for 'justificativa', the character length must be smaller than or equal to 2048.";
        }

        if ((mb_strlen($this->container['justificativa']) < 0)) {
            $invalidProperties[] = "invalid value for 'justificativa', the character length must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets numero_ata_registro_preco
     *
     * @return string
     */
    public function getNumeroAtaRegistroPreco()
    {
        return $this->container['numero_ata_registro_preco'];
    }

    /**
     * Sets numero_ata_registro_preco
     *
     * @param string $numero_ata_registro_preco numero_ata_registro_preco
     *
     * @return self
     */
    public function setNumeroAtaRegistroPreco($numero_ata_registro_preco)
    {
        if (is_null($numero_ata_registro_preco)) {
            throw new \InvalidArgumentException('non-nullable numero_ata_registro_preco cannot be null');
        }
        $this->container['numero_ata_registro_preco'] = $numero_ata_registro_preco;

        return $this;
    }

    /**
     * Gets ano_ata
     *
     * @return int
     */
    public function getAnoAta()
    {
        return $this->container['ano_ata'];
    }

    /**
     * Sets ano_ata
     *
     * @param int $ano_ata ano_ata
     *
     * @return self
     */
    public function setAnoAta($ano_ata)
    {
        if (is_null($ano_ata)) {
            throw new \InvalidArgumentException('non-nullable ano_ata cannot be null');
        }
        $this->container['ano_ata'] = $ano_ata;

        return $this;
    }

    /**
     * Gets data_assinatura
     *
     * @return \DateTime
     */
    public function getDataAssinatura()
    {
        return $this->container['data_assinatura'];
    }

    /**
     * Sets data_assinatura
     *
     * @param \DateTime $data_assinatura data_assinatura
     *
     * @return self
     */
    public function setDataAssinatura($data_assinatura)
    {
        if (is_null($data_assinatura)) {
            throw new \InvalidArgumentException('non-nullable data_assinatura cannot be null');
        }
        $this->container['data_assinatura'] = $data_assinatura;

        return $this;
    }

    /**
     * Gets data_vigencia_inicio
     *
     * @return \DateTime
     */
    public function getDataVigenciaInicio()
    {
        return $this->container['data_vigencia_inicio'];
    }

    /**
     * Sets data_vigencia_inicio
     *
     * @param \DateTime $data_vigencia_inicio data_vigencia_inicio
     *
     * @return self
     */
    public function setDataVigenciaInicio($data_vigencia_inicio)
    {
        if (is_null($data_vigencia_inicio)) {
            throw new \InvalidArgumentException('non-nullable data_vigencia_inicio cannot be null');
        }
        $this->container['data_vigencia_inicio'] = $data_vigencia_inicio;

        return $this;
    }

    /**
     * Gets data_vigencia_fim
     *
     * @return \DateTime
     */
    public function getDataVigenciaFim()
    {
        return $this->container['data_vigencia_fim'];
    }

    /**
     * Sets data_vigencia_fim
     *
     * @param \DateTime $data_vigencia_fim data_vigencia_fim
     *
     * @return self
     */
    public function setDataVigenciaFim($data_vigencia_fim)
    {
        if (is_null($data_vigencia_fim)) {
            throw new \InvalidArgumentException('non-nullable data_vigencia_fim cannot be null');
        }
        $this->container['data_vigencia_fim'] = $data_vigencia_fim;

        return $this;
    }

    /**
     * Gets cancelado
     *
     * @return bool
     */
    public function getCancelado()
    {
        return $this->container['cancelado'];
    }

    /**
     * Sets cancelado
     *
     * @param bool $cancelado cancelado
     *
     * @return self
     */
    public function setCancelado($cancelado)
    {
        if (is_null($cancelado)) {
            throw new \InvalidArgumentException('non-nullable cancelado cannot be null');
        }
        $this->container['cancelado'] = $cancelado;

        return $this;
    }

    /**
     * Gets data_cancelamento
     *
     * @return \DateTime|null
     */
    public function getDataCancelamento()
    {
        return $this->container['data_cancelamento'];
    }

    /**
     * Sets data_cancelamento
     *
     * @param \DateTime|null $data_cancelamento data_cancelamento
     *
     * @return self
     */
    public function setDataCancelamento($data_cancelamento)
    {
        if (is_null($data_cancelamento)) {
            throw new \InvalidArgumentException('non-nullable data_cancelamento cannot be null');
        }
        $this->container['data_cancelamento'] = $data_cancelamento;

        return $this;
    }

    /**
     * Gets justificativa
     *
     * @return string
     */
    public function getJustificativa()
    {
        return $this->container['justificativa'];
    }

    /**
     * Sets justificativa
     *
     * @param string $justificativa justificativa
     *
     * @return self
     */
    public function setJustificativa($justificativa)
    {
        if (is_null($justificativa)) {
            throw new \InvalidArgumentException('non-nullable justificativa cannot be null');
        }
        if ((mb_strlen($justificativa) > 2048)) {
            throw new \InvalidArgumentException('invalid length for $justificativa when calling AtaRegistroPrecoAlteracaoDTO., must be smaller than or equal to 2048.');
        }
        if ((mb_strlen($justificativa) < 0)) {
            throw new \InvalidArgumentException('invalid length for $justificativa when calling AtaRegistroPrecoAlteracaoDTO., must be bigger than or equal to 0.');
        }

        $this->container['justificativa'] = $justificativa;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


