<?php
/**
 * RecuperarCompraItemResultadoDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RecuperarCompraItemResultadoDTO Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RecuperarCompraItemResultadoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RecuperarCompraItemResultadoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'data_atualizacao' => '\DateTime',
        'ni_fornecedor' => 'string',
        'tipo_pessoa' => 'string',
        'data_inclusao' => '\DateTime',
        'numero_item' => 'int',
        'data_cancelamento' => '\DateTime',
        'nome_razao_social_fornecedor' => 'string',
        'codigo_pais' => 'string',
        'porte_fornecedor_id' => 'string',
        'quantidade_homologada' => 'float',
        'valor_unitario_homologado' => 'float',
        'valor_total_homologado' => 'float',
        'percentual_desconto' => 'float',
        'indicador_subcontratacao' => 'bool',
        'ordem_classificacao_srp' => 'int',
        'data_resultado' => '\DateTime',
        'motivo_cancelamento' => 'string',
        'porte_fornecedor_nome' => 'string',
        'situacao_compra_item_resultado_nome' => 'string',
        'sequencial_resultado' => 'int',
        'natureza_juridica_nome' => 'string',
        'natureza_juridica_id' => 'string',
        'numero_controle_pncp_compra' => 'string',
        'situacao_compra_item_resultado_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'data_atualizacao' => 'date-time',
        'ni_fornecedor' => null,
        'tipo_pessoa' => null,
        'data_inclusao' => 'date-time',
        'numero_item' => 'int32',
        'data_cancelamento' => 'date-time',
        'nome_razao_social_fornecedor' => null,
        'codigo_pais' => null,
        'porte_fornecedor_id' => null,
        'quantidade_homologada' => null,
        'valor_unitario_homologado' => null,
        'valor_total_homologado' => null,
        'percentual_desconto' => null,
        'indicador_subcontratacao' => null,
        'ordem_classificacao_srp' => 'int32',
        'data_resultado' => 'date',
        'motivo_cancelamento' => null,
        'porte_fornecedor_nome' => null,
        'situacao_compra_item_resultado_nome' => null,
        'sequencial_resultado' => 'int32',
        'natureza_juridica_nome' => null,
        'natureza_juridica_id' => null,
        'numero_controle_pncp_compra' => null,
        'situacao_compra_item_resultado_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'data_atualizacao' => false,
		'ni_fornecedor' => false,
		'tipo_pessoa' => false,
		'data_inclusao' => false,
		'numero_item' => false,
		'data_cancelamento' => false,
		'nome_razao_social_fornecedor' => false,
		'codigo_pais' => false,
		'porte_fornecedor_id' => false,
		'quantidade_homologada' => false,
		'valor_unitario_homologado' => false,
		'valor_total_homologado' => false,
		'percentual_desconto' => false,
		'indicador_subcontratacao' => false,
		'ordem_classificacao_srp' => false,
		'data_resultado' => false,
		'motivo_cancelamento' => false,
		'porte_fornecedor_nome' => false,
		'situacao_compra_item_resultado_nome' => false,
		'sequencial_resultado' => false,
		'natureza_juridica_nome' => false,
		'natureza_juridica_id' => false,
		'numero_controle_pncp_compra' => false,
		'situacao_compra_item_resultado_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'data_atualizacao' => 'dataAtualizacao',
        'ni_fornecedor' => 'niFornecedor',
        'tipo_pessoa' => 'tipoPessoa',
        'data_inclusao' => 'dataInclusao',
        'numero_item' => 'numeroItem',
        'data_cancelamento' => 'dataCancelamento',
        'nome_razao_social_fornecedor' => 'nomeRazaoSocialFornecedor',
        'codigo_pais' => 'codigoPais',
        'porte_fornecedor_id' => 'porteFornecedorId',
        'quantidade_homologada' => 'quantidadeHomologada',
        'valor_unitario_homologado' => 'valorUnitarioHomologado',
        'valor_total_homologado' => 'valorTotalHomologado',
        'percentual_desconto' => 'percentualDesconto',
        'indicador_subcontratacao' => 'indicadorSubcontratacao',
        'ordem_classificacao_srp' => 'ordemClassificacaoSrp',
        'data_resultado' => 'dataResultado',
        'motivo_cancelamento' => 'motivoCancelamento',
        'porte_fornecedor_nome' => 'porteFornecedorNome',
        'situacao_compra_item_resultado_nome' => 'situacaoCompraItemResultadoNome',
        'sequencial_resultado' => 'sequencialResultado',
        'natureza_juridica_nome' => 'naturezaJuridicaNome',
        'natureza_juridica_id' => 'naturezaJuridicaId',
        'numero_controle_pncp_compra' => 'numeroControlePNCPCompra',
        'situacao_compra_item_resultado_id' => 'situacaoCompraItemResultadoId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'data_atualizacao' => 'setDataAtualizacao',
        'ni_fornecedor' => 'setNiFornecedor',
        'tipo_pessoa' => 'setTipoPessoa',
        'data_inclusao' => 'setDataInclusao',
        'numero_item' => 'setNumeroItem',
        'data_cancelamento' => 'setDataCancelamento',
        'nome_razao_social_fornecedor' => 'setNomeRazaoSocialFornecedor',
        'codigo_pais' => 'setCodigoPais',
        'porte_fornecedor_id' => 'setPorteFornecedorId',
        'quantidade_homologada' => 'setQuantidadeHomologada',
        'valor_unitario_homologado' => 'setValorUnitarioHomologado',
        'valor_total_homologado' => 'setValorTotalHomologado',
        'percentual_desconto' => 'setPercentualDesconto',
        'indicador_subcontratacao' => 'setIndicadorSubcontratacao',
        'ordem_classificacao_srp' => 'setOrdemClassificacaoSrp',
        'data_resultado' => 'setDataResultado',
        'motivo_cancelamento' => 'setMotivoCancelamento',
        'porte_fornecedor_nome' => 'setPorteFornecedorNome',
        'situacao_compra_item_resultado_nome' => 'setSituacaoCompraItemResultadoNome',
        'sequencial_resultado' => 'setSequencialResultado',
        'natureza_juridica_nome' => 'setNaturezaJuridicaNome',
        'natureza_juridica_id' => 'setNaturezaJuridicaId',
        'numero_controle_pncp_compra' => 'setNumeroControlePncpCompra',
        'situacao_compra_item_resultado_id' => 'setSituacaoCompraItemResultadoId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'data_atualizacao' => 'getDataAtualizacao',
        'ni_fornecedor' => 'getNiFornecedor',
        'tipo_pessoa' => 'getTipoPessoa',
        'data_inclusao' => 'getDataInclusao',
        'numero_item' => 'getNumeroItem',
        'data_cancelamento' => 'getDataCancelamento',
        'nome_razao_social_fornecedor' => 'getNomeRazaoSocialFornecedor',
        'codigo_pais' => 'getCodigoPais',
        'porte_fornecedor_id' => 'getPorteFornecedorId',
        'quantidade_homologada' => 'getQuantidadeHomologada',
        'valor_unitario_homologado' => 'getValorUnitarioHomologado',
        'valor_total_homologado' => 'getValorTotalHomologado',
        'percentual_desconto' => 'getPercentualDesconto',
        'indicador_subcontratacao' => 'getIndicadorSubcontratacao',
        'ordem_classificacao_srp' => 'getOrdemClassificacaoSrp',
        'data_resultado' => 'getDataResultado',
        'motivo_cancelamento' => 'getMotivoCancelamento',
        'porte_fornecedor_nome' => 'getPorteFornecedorNome',
        'situacao_compra_item_resultado_nome' => 'getSituacaoCompraItemResultadoNome',
        'sequencial_resultado' => 'getSequencialResultado',
        'natureza_juridica_nome' => 'getNaturezaJuridicaNome',
        'natureza_juridica_id' => 'getNaturezaJuridicaId',
        'numero_controle_pncp_compra' => 'getNumeroControlePncpCompra',
        'situacao_compra_item_resultado_id' => 'getSituacaoCompraItemResultadoId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TIPO_PESSOA_PJ = 'PJ';
    public const TIPO_PESSOA_PF = 'PF';
    public const TIPO_PESSOA_PE = 'PE';
    public const PORTE_FORNECEDOR_ID__1 = '1';
    public const PORTE_FORNECEDOR_ID__2 = '2';
    public const PORTE_FORNECEDOR_ID__3 = '3';
    public const PORTE_FORNECEDOR_ID__4 = '4';
    public const PORTE_FORNECEDOR_ID__5 = '5';
    public const SITUACAO_COMPRA_ITEM_RESULTADO_ID__1 = '1';
    public const SITUACAO_COMPRA_ITEM_RESULTADO_ID__2 = '2';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTipoPessoaAllowableValues()
    {
        return [
            self::TIPO_PESSOA_PJ,
            self::TIPO_PESSOA_PF,
            self::TIPO_PESSOA_PE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPorteFornecedorIdAllowableValues()
    {
        return [
            self::PORTE_FORNECEDOR_ID__1,
            self::PORTE_FORNECEDOR_ID__2,
            self::PORTE_FORNECEDOR_ID__3,
            self::PORTE_FORNECEDOR_ID__4,
            self::PORTE_FORNECEDOR_ID__5,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSituacaoCompraItemResultadoIdAllowableValues()
    {
        return [
            self::SITUACAO_COMPRA_ITEM_RESULTADO_ID__1,
            self::SITUACAO_COMPRA_ITEM_RESULTADO_ID__2,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('data_atualizacao', $data ?? [], null);
        $this->setIfExists('ni_fornecedor', $data ?? [], null);
        $this->setIfExists('tipo_pessoa', $data ?? [], null);
        $this->setIfExists('data_inclusao', $data ?? [], null);
        $this->setIfExists('numero_item', $data ?? [], null);
        $this->setIfExists('data_cancelamento', $data ?? [], null);
        $this->setIfExists('nome_razao_social_fornecedor', $data ?? [], null);
        $this->setIfExists('codigo_pais', $data ?? [], null);
        $this->setIfExists('porte_fornecedor_id', $data ?? [], null);
        $this->setIfExists('quantidade_homologada', $data ?? [], null);
        $this->setIfExists('valor_unitario_homologado', $data ?? [], null);
        $this->setIfExists('valor_total_homologado', $data ?? [], null);
        $this->setIfExists('percentual_desconto', $data ?? [], null);
        $this->setIfExists('indicador_subcontratacao', $data ?? [], null);
        $this->setIfExists('ordem_classificacao_srp', $data ?? [], null);
        $this->setIfExists('data_resultado', $data ?? [], null);
        $this->setIfExists('motivo_cancelamento', $data ?? [], null);
        $this->setIfExists('porte_fornecedor_nome', $data ?? [], null);
        $this->setIfExists('situacao_compra_item_resultado_nome', $data ?? [], null);
        $this->setIfExists('sequencial_resultado', $data ?? [], null);
        $this->setIfExists('natureza_juridica_nome', $data ?? [], null);
        $this->setIfExists('natureza_juridica_id', $data ?? [], null);
        $this->setIfExists('numero_controle_pncp_compra', $data ?? [], null);
        $this->setIfExists('situacao_compra_item_resultado_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTipoPessoaAllowableValues();
        if (!is_null($this->container['tipo_pessoa']) && !in_array($this->container['tipo_pessoa'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tipo_pessoa', must be one of '%s'",
                $this->container['tipo_pessoa'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPorteFornecedorIdAllowableValues();
        if (!is_null($this->container['porte_fornecedor_id']) && !in_array($this->container['porte_fornecedor_id'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'porte_fornecedor_id', must be one of '%s'",
                $this->container['porte_fornecedor_id'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSituacaoCompraItemResultadoIdAllowableValues();
        if (!is_null($this->container['situacao_compra_item_resultado_id']) && !in_array($this->container['situacao_compra_item_resultado_id'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'situacao_compra_item_resultado_id', must be one of '%s'",
                $this->container['situacao_compra_item_resultado_id'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets data_atualizacao
     *
     * @return \DateTime|null
     */
    public function getDataAtualizacao()
    {
        return $this->container['data_atualizacao'];
    }

    /**
     * Sets data_atualizacao
     *
     * @param \DateTime|null $data_atualizacao data_atualizacao
     *
     * @return self
     */
    public function setDataAtualizacao($data_atualizacao)
    {
        if (is_null($data_atualizacao)) {
            throw new \InvalidArgumentException('non-nullable data_atualizacao cannot be null');
        }
        $this->container['data_atualizacao'] = $data_atualizacao;

        return $this;
    }

    /**
     * Gets ni_fornecedor
     *
     * @return string|null
     */
    public function getNiFornecedor()
    {
        return $this->container['ni_fornecedor'];
    }

    /**
     * Sets ni_fornecedor
     *
     * @param string|null $ni_fornecedor ni_fornecedor
     *
     * @return self
     */
    public function setNiFornecedor($ni_fornecedor)
    {
        if (is_null($ni_fornecedor)) {
            throw new \InvalidArgumentException('non-nullable ni_fornecedor cannot be null');
        }
        $this->container['ni_fornecedor'] = $ni_fornecedor;

        return $this;
    }

    /**
     * Gets tipo_pessoa
     *
     * @return string|null
     */
    public function getTipoPessoa()
    {
        return $this->container['tipo_pessoa'];
    }

    /**
     * Sets tipo_pessoa
     *
     * @param string|null $tipo_pessoa tipo_pessoa
     *
     * @return self
     */
    public function setTipoPessoa($tipo_pessoa)
    {
        if (is_null($tipo_pessoa)) {
            throw new \InvalidArgumentException('non-nullable tipo_pessoa cannot be null');
        }
        $allowedValues = $this->getTipoPessoaAllowableValues();
        if (!in_array($tipo_pessoa, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tipo_pessoa', must be one of '%s'",
                    $tipo_pessoa,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tipo_pessoa'] = $tipo_pessoa;

        return $this;
    }

    /**
     * Gets data_inclusao
     *
     * @return \DateTime|null
     */
    public function getDataInclusao()
    {
        return $this->container['data_inclusao'];
    }

    /**
     * Sets data_inclusao
     *
     * @param \DateTime|null $data_inclusao data_inclusao
     *
     * @return self
     */
    public function setDataInclusao($data_inclusao)
    {
        if (is_null($data_inclusao)) {
            throw new \InvalidArgumentException('non-nullable data_inclusao cannot be null');
        }
        $this->container['data_inclusao'] = $data_inclusao;

        return $this;
    }

    /**
     * Gets numero_item
     *
     * @return int|null
     */
    public function getNumeroItem()
    {
        return $this->container['numero_item'];
    }

    /**
     * Sets numero_item
     *
     * @param int|null $numero_item numero_item
     *
     * @return self
     */
    public function setNumeroItem($numero_item)
    {
        if (is_null($numero_item)) {
            throw new \InvalidArgumentException('non-nullable numero_item cannot be null');
        }
        $this->container['numero_item'] = $numero_item;

        return $this;
    }

    /**
     * Gets data_cancelamento
     *
     * @return \DateTime|null
     */
    public function getDataCancelamento()
    {
        return $this->container['data_cancelamento'];
    }

    /**
     * Sets data_cancelamento
     *
     * @param \DateTime|null $data_cancelamento data_cancelamento
     *
     * @return self
     */
    public function setDataCancelamento($data_cancelamento)
    {
        if (is_null($data_cancelamento)) {
            throw new \InvalidArgumentException('non-nullable data_cancelamento cannot be null');
        }
        $this->container['data_cancelamento'] = $data_cancelamento;

        return $this;
    }

    /**
     * Gets nome_razao_social_fornecedor
     *
     * @return string|null
     */
    public function getNomeRazaoSocialFornecedor()
    {
        return $this->container['nome_razao_social_fornecedor'];
    }

    /**
     * Sets nome_razao_social_fornecedor
     *
     * @param string|null $nome_razao_social_fornecedor nome_razao_social_fornecedor
     *
     * @return self
     */
    public function setNomeRazaoSocialFornecedor($nome_razao_social_fornecedor)
    {
        if (is_null($nome_razao_social_fornecedor)) {
            throw new \InvalidArgumentException('non-nullable nome_razao_social_fornecedor cannot be null');
        }
        $this->container['nome_razao_social_fornecedor'] = $nome_razao_social_fornecedor;

        return $this;
    }

    /**
     * Gets codigo_pais
     *
     * @return string|null
     */
    public function getCodigoPais()
    {
        return $this->container['codigo_pais'];
    }

    /**
     * Sets codigo_pais
     *
     * @param string|null $codigo_pais codigo_pais
     *
     * @return self
     */
    public function setCodigoPais($codigo_pais)
    {
        if (is_null($codigo_pais)) {
            throw new \InvalidArgumentException('non-nullable codigo_pais cannot be null');
        }
        $this->container['codigo_pais'] = $codigo_pais;

        return $this;
    }

    /**
     * Gets porte_fornecedor_id
     *
     * @return string|null
     */
    public function getPorteFornecedorId()
    {
        return $this->container['porte_fornecedor_id'];
    }

    /**
     * Sets porte_fornecedor_id
     *
     * @param string|null $porte_fornecedor_id porte_fornecedor_id
     *
     * @return self
     */
    public function setPorteFornecedorId($porte_fornecedor_id)
    {
        if (is_null($porte_fornecedor_id)) {
            throw new \InvalidArgumentException('non-nullable porte_fornecedor_id cannot be null');
        }
        $allowedValues = $this->getPorteFornecedorIdAllowableValues();
        if (!in_array($porte_fornecedor_id, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'porte_fornecedor_id', must be one of '%s'",
                    $porte_fornecedor_id,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['porte_fornecedor_id'] = $porte_fornecedor_id;

        return $this;
    }

    /**
     * Gets quantidade_homologada
     *
     * @return float|null
     */
    public function getQuantidadeHomologada()
    {
        return $this->container['quantidade_homologada'];
    }

    /**
     * Sets quantidade_homologada
     *
     * @param float|null $quantidade_homologada quantidade_homologada
     *
     * @return self
     */
    public function setQuantidadeHomologada($quantidade_homologada)
    {
        if (is_null($quantidade_homologada)) {
            throw new \InvalidArgumentException('non-nullable quantidade_homologada cannot be null');
        }
        $this->container['quantidade_homologada'] = $quantidade_homologada;

        return $this;
    }

    /**
     * Gets valor_unitario_homologado
     *
     * @return float|null
     */
    public function getValorUnitarioHomologado()
    {
        return $this->container['valor_unitario_homologado'];
    }

    /**
     * Sets valor_unitario_homologado
     *
     * @param float|null $valor_unitario_homologado valor_unitario_homologado
     *
     * @return self
     */
    public function setValorUnitarioHomologado($valor_unitario_homologado)
    {
        if (is_null($valor_unitario_homologado)) {
            throw new \InvalidArgumentException('non-nullable valor_unitario_homologado cannot be null');
        }
        $this->container['valor_unitario_homologado'] = $valor_unitario_homologado;

        return $this;
    }

    /**
     * Gets valor_total_homologado
     *
     * @return float|null
     */
    public function getValorTotalHomologado()
    {
        return $this->container['valor_total_homologado'];
    }

    /**
     * Sets valor_total_homologado
     *
     * @param float|null $valor_total_homologado valor_total_homologado
     *
     * @return self
     */
    public function setValorTotalHomologado($valor_total_homologado)
    {
        if (is_null($valor_total_homologado)) {
            throw new \InvalidArgumentException('non-nullable valor_total_homologado cannot be null');
        }
        $this->container['valor_total_homologado'] = $valor_total_homologado;

        return $this;
    }

    /**
     * Gets percentual_desconto
     *
     * @return float|null
     */
    public function getPercentualDesconto()
    {
        return $this->container['percentual_desconto'];
    }

    /**
     * Sets percentual_desconto
     *
     * @param float|null $percentual_desconto percentual_desconto
     *
     * @return self
     */
    public function setPercentualDesconto($percentual_desconto)
    {
        if (is_null($percentual_desconto)) {
            throw new \InvalidArgumentException('non-nullable percentual_desconto cannot be null');
        }
        $this->container['percentual_desconto'] = $percentual_desconto;

        return $this;
    }

    /**
     * Gets indicador_subcontratacao
     *
     * @return bool|null
     */
    public function getIndicadorSubcontratacao()
    {
        return $this->container['indicador_subcontratacao'];
    }

    /**
     * Sets indicador_subcontratacao
     *
     * @param bool|null $indicador_subcontratacao indicador_subcontratacao
     *
     * @return self
     */
    public function setIndicadorSubcontratacao($indicador_subcontratacao)
    {
        if (is_null($indicador_subcontratacao)) {
            throw new \InvalidArgumentException('non-nullable indicador_subcontratacao cannot be null');
        }
        $this->container['indicador_subcontratacao'] = $indicador_subcontratacao;

        return $this;
    }

    /**
     * Gets ordem_classificacao_srp
     *
     * @return int|null
     */
    public function getOrdemClassificacaoSrp()
    {
        return $this->container['ordem_classificacao_srp'];
    }

    /**
     * Sets ordem_classificacao_srp
     *
     * @param int|null $ordem_classificacao_srp ordem_classificacao_srp
     *
     * @return self
     */
    public function setOrdemClassificacaoSrp($ordem_classificacao_srp)
    {
        if (is_null($ordem_classificacao_srp)) {
            throw new \InvalidArgumentException('non-nullable ordem_classificacao_srp cannot be null');
        }
        $this->container['ordem_classificacao_srp'] = $ordem_classificacao_srp;

        return $this;
    }

    /**
     * Gets data_resultado
     *
     * @return \DateTime|null
     */
    public function getDataResultado()
    {
        return $this->container['data_resultado'];
    }

    /**
     * Sets data_resultado
     *
     * @param \DateTime|null $data_resultado data_resultado
     *
     * @return self
     */
    public function setDataResultado($data_resultado)
    {
        if (is_null($data_resultado)) {
            throw new \InvalidArgumentException('non-nullable data_resultado cannot be null');
        }
        $this->container['data_resultado'] = $data_resultado;

        return $this;
    }

    /**
     * Gets motivo_cancelamento
     *
     * @return string|null
     */
    public function getMotivoCancelamento()
    {
        return $this->container['motivo_cancelamento'];
    }

    /**
     * Sets motivo_cancelamento
     *
     * @param string|null $motivo_cancelamento motivo_cancelamento
     *
     * @return self
     */
    public function setMotivoCancelamento($motivo_cancelamento)
    {
        if (is_null($motivo_cancelamento)) {
            throw new \InvalidArgumentException('non-nullable motivo_cancelamento cannot be null');
        }
        $this->container['motivo_cancelamento'] = $motivo_cancelamento;

        return $this;
    }

    /**
     * Gets porte_fornecedor_nome
     *
     * @return string|null
     */
    public function getPorteFornecedorNome()
    {
        return $this->container['porte_fornecedor_nome'];
    }

    /**
     * Sets porte_fornecedor_nome
     *
     * @param string|null $porte_fornecedor_nome porte_fornecedor_nome
     *
     * @return self
     */
    public function setPorteFornecedorNome($porte_fornecedor_nome)
    {
        if (is_null($porte_fornecedor_nome)) {
            throw new \InvalidArgumentException('non-nullable porte_fornecedor_nome cannot be null');
        }
        $this->container['porte_fornecedor_nome'] = $porte_fornecedor_nome;

        return $this;
    }

    /**
     * Gets situacao_compra_item_resultado_nome
     *
     * @return string|null
     */
    public function getSituacaoCompraItemResultadoNome()
    {
        return $this->container['situacao_compra_item_resultado_nome'];
    }

    /**
     * Sets situacao_compra_item_resultado_nome
     *
     * @param string|null $situacao_compra_item_resultado_nome situacao_compra_item_resultado_nome
     *
     * @return self
     */
    public function setSituacaoCompraItemResultadoNome($situacao_compra_item_resultado_nome)
    {
        if (is_null($situacao_compra_item_resultado_nome)) {
            throw new \InvalidArgumentException('non-nullable situacao_compra_item_resultado_nome cannot be null');
        }
        $this->container['situacao_compra_item_resultado_nome'] = $situacao_compra_item_resultado_nome;

        return $this;
    }

    /**
     * Gets sequencial_resultado
     *
     * @return int|null
     */
    public function getSequencialResultado()
    {
        return $this->container['sequencial_resultado'];
    }

    /**
     * Sets sequencial_resultado
     *
     * @param int|null $sequencial_resultado sequencial_resultado
     *
     * @return self
     */
    public function setSequencialResultado($sequencial_resultado)
    {
        if (is_null($sequencial_resultado)) {
            throw new \InvalidArgumentException('non-nullable sequencial_resultado cannot be null');
        }
        $this->container['sequencial_resultado'] = $sequencial_resultado;

        return $this;
    }

    /**
     * Gets natureza_juridica_nome
     *
     * @return string|null
     */
    public function getNaturezaJuridicaNome()
    {
        return $this->container['natureza_juridica_nome'];
    }

    /**
     * Sets natureza_juridica_nome
     *
     * @param string|null $natureza_juridica_nome natureza_juridica_nome
     *
     * @return self
     */
    public function setNaturezaJuridicaNome($natureza_juridica_nome)
    {
        if (is_null($natureza_juridica_nome)) {
            throw new \InvalidArgumentException('non-nullable natureza_juridica_nome cannot be null');
        }
        $this->container['natureza_juridica_nome'] = $natureza_juridica_nome;

        return $this;
    }

    /**
     * Gets natureza_juridica_id
     *
     * @return string|null
     */
    public function getNaturezaJuridicaId()
    {
        return $this->container['natureza_juridica_id'];
    }

    /**
     * Sets natureza_juridica_id
     *
     * @param string|null $natureza_juridica_id natureza_juridica_id
     *
     * @return self
     */
    public function setNaturezaJuridicaId($natureza_juridica_id)
    {
        if (is_null($natureza_juridica_id)) {
            throw new \InvalidArgumentException('non-nullable natureza_juridica_id cannot be null');
        }
        $this->container['natureza_juridica_id'] = $natureza_juridica_id;

        return $this;
    }

    /**
     * Gets numero_controle_pncp_compra
     *
     * @return string|null
     */
    public function getNumeroControlePncpCompra()
    {
        return $this->container['numero_controle_pncp_compra'];
    }

    /**
     * Sets numero_controle_pncp_compra
     *
     * @param string|null $numero_controle_pncp_compra numero_controle_pncp_compra
     *
     * @return self
     */
    public function setNumeroControlePncpCompra($numero_controle_pncp_compra)
    {
        if (is_null($numero_controle_pncp_compra)) {
            throw new \InvalidArgumentException('non-nullable numero_controle_pncp_compra cannot be null');
        }
        $this->container['numero_controle_pncp_compra'] = $numero_controle_pncp_compra;

        return $this;
    }

    /**
     * Gets situacao_compra_item_resultado_id
     *
     * @return string|null
     */
    public function getSituacaoCompraItemResultadoId()
    {
        return $this->container['situacao_compra_item_resultado_id'];
    }

    /**
     * Sets situacao_compra_item_resultado_id
     *
     * @param string|null $situacao_compra_item_resultado_id situacao_compra_item_resultado_id
     *
     * @return self
     */
    public function setSituacaoCompraItemResultadoId($situacao_compra_item_resultado_id)
    {
        if (is_null($situacao_compra_item_resultado_id)) {
            throw new \InvalidArgumentException('non-nullable situacao_compra_item_resultado_id cannot be null');
        }
        $allowedValues = $this->getSituacaoCompraItemResultadoIdAllowableValues();
        if (!in_array($situacao_compra_item_resultado_id, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'situacao_compra_item_resultado_id', must be one of '%s'",
                    $situacao_compra_item_resultado_id,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['situacao_compra_item_resultado_id'] = $situacao_compra_item_resultado_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


