<?php
/**
 * AlterarContratoDTOTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AlterarContratoDTOTest Class Doc Comment
 *
 * @category    Class
 * @description AlterarContratoDTO
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AlterarContratoDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AlterarContratoDTO"
     */
    public function testAlterarContratoDTO()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cnpj_compra"
     */
    public function testPropertyCnpjCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ano_compra"
     */
    public function testPropertyAnoCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sequencial_compra"
     */
    public function testPropertySequencialCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_contrato_id"
     */
    public function testPropertyTipoContratoId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_contrato_empenho"
     */
    public function testPropertyNumeroContratoEmpenho()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "processo"
     */
    public function testPropertyProcesso()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "categoria_processo_id"
     */
    public function testPropertyCategoriaProcessoId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ni_fornecedor"
     */
    public function testPropertyNiFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pessoa_fornecedor"
     */
    public function testPropertyTipoPessoaFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nome_razao_social_fornecedor"
     */
    public function testPropertyNomeRazaoSocialFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "receita"
     */
    public function testPropertyReceita()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codigo_unidade"
     */
    public function testPropertyCodigoUnidade()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objeto_contrato"
     */
    public function testPropertyObjetoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_inicial"
     */
    public function testPropertyValorInicial()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_parcelas"
     */
    public function testPropertyNumeroParcelas()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_parcela"
     */
    public function testPropertyValorParcela()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_global"
     */
    public function testPropertyValorGlobal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_assinatura"
     */
    public function testPropertyDataAssinatura()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_vigencia_inicio"
     */
    public function testPropertyDataVigenciaInicio()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_vigencia_fim"
     */
    public function testPropertyDataVigenciaFim()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_acumulado"
     */
    public function testPropertyValorAcumulado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ni_fornecedor_sub_contratado"
     */
    public function testPropertyNiFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pessoa_fornecedor_sub_contratado"
     */
    public function testPropertyTipoPessoaFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nome_razao_social_fornecedor_sub_contratado"
     */
    public function testPropertyNomeRazaoSocialFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "informacao_complementar"
     */
    public function testPropertyInformacaoComplementar()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "url_cipi"
     */
    public function testPropertyUrlCipi()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "identificador_cipi"
     */
    public function testPropertyIdentificadorCipi()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cnpj_orgao_sub_rogado"
     */
    public function testPropertyCnpjOrgaoSubRogado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codigo_unidade_sub_rogada"
     */
    public function testPropertyCodigoUnidadeSubRogada()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "justificativa"
     */
    public function testPropertyJustificativa()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
