<?php
/**
 * AlterarCompraDTOTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AlterarCompraDTOTest Class Doc Comment
 *
 * @category    Class
 * @description AlterarCompraDTO
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AlterarCompraDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AlterarCompraDTO"
     */
    public function testAlterarCompraDTO()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_instrumento_convocatorio_id"
     */
    public function testPropertyTipoInstrumentoConvocatorioId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "modalidade_id"
     */
    public function testPropertyModalidadeId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "modo_disputa_id"
     */
    public function testPropertyModoDisputaId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_compra"
     */
    public function testPropertyNumeroCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_processo"
     */
    public function testPropertyNumeroProcesso()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "situacao_compra_id"
     */
    public function testPropertySituacaoCompraId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objeto_compra"
     */
    public function testPropertyObjetoCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "informacao_complementar"
     */
    public function testPropertyInformacaoComplementar()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amparo_legal_id"
     */
    public function testPropertyAmparoLegalId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cnpj_orgao_sub_rogado"
     */
    public function testPropertyCnpjOrgaoSubRogado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codigo_unidade_sub_rogada"
     */
    public function testPropertyCodigoUnidadeSubRogada()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "srp"
     */
    public function testPropertySrp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_abertura_proposta"
     */
    public function testPropertyDataAberturaProposta()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_encerramento_proposta"
     */
    public function testPropertyDataEncerramentoProposta()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codigo_unidade_compradora"
     */
    public function testPropertyCodigoUnidadeCompradora()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "link_sistema_origem"
     */
    public function testPropertyLinkSistemaOrigem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "justificativa"
     */
    public function testPropertyJustificativa()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "justificativa_presencial"
     */
    public function testPropertyJustificativaPresencial()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
