<?php
/**
 * IncluirTermoContratoDTOTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * IncluirTermoContratoDTOTest Class Doc Comment
 *
 * @category    Class
 * @description IncluirTermoContratoDTO
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IncluirTermoContratoDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IncluirTermoContratoDTO"
     */
    public function testIncluirTermoContratoDTO()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_termo_contrato_id"
     */
    public function testPropertyTipoTermoContratoId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_termo_contrato"
     */
    public function testPropertyNumeroTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objeto_termo_contrato"
     */
    public function testPropertyObjetoTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_acrescimo_supressao"
     */
    public function testPropertyQualificacaoAcrescimoSupressao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_vigencia"
     */
    public function testPropertyQualificacaoVigencia()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_fornecedor"
     */
    public function testPropertyQualificacaoFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_informativo"
     */
    public function testPropertyQualificacaoInformativo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_reajuste"
     */
    public function testPropertyQualificacaoReajuste()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_assinatura"
     */
    public function testPropertyDataAssinatura()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ni_fornecedor"
     */
    public function testPropertyNiFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pessoa_fornecedor"
     */
    public function testPropertyTipoPessoaFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nome_razao_social_fornecedor"
     */
    public function testPropertyNomeRazaoSocialFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ni_fornecedor_sub_contratado"
     */
    public function testPropertyNiFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pessoa_fornecedor_sub_contratado"
     */
    public function testPropertyTipoPessoaFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nome_razao_social_fornecedor_sub_contratado"
     */
    public function testPropertyNomeRazaoSocialFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "informativo_observacao"
     */
    public function testPropertyInformativoObservacao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fundamento_legal"
     */
    public function testPropertyFundamentoLegal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_acrescido"
     */
    public function testPropertyValorAcrescido()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_parcelas"
     */
    public function testPropertyNumeroParcelas()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_parcela"
     */
    public function testPropertyValorParcela()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_global"
     */
    public function testPropertyValorGlobal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "prazo_aditado_dias"
     */
    public function testPropertyPrazoAditadoDias()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_vigencia_inicio"
     */
    public function testPropertyDataVigenciaInicio()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_vigencia_fim"
     */
    public function testPropertyDataVigenciaFim()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
