<?php
/**
 * RecuperarCompraItemResultadoDTOTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RecuperarCompraItemResultadoDTOTest Class Doc Comment
 *
 * @category    Class
 * @description RecuperarCompraItemResultadoDTO
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RecuperarCompraItemResultadoDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RecuperarCompraItemResultadoDTO"
     */
    public function testRecuperarCompraItemResultadoDTO()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_atualizacao"
     */
    public function testPropertyDataAtualizacao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ni_fornecedor"
     */
    public function testPropertyNiFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pessoa"
     */
    public function testPropertyTipoPessoa()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_inclusao"
     */
    public function testPropertyDataInclusao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_item"
     */
    public function testPropertyNumeroItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_cancelamento"
     */
    public function testPropertyDataCancelamento()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nome_razao_social_fornecedor"
     */
    public function testPropertyNomeRazaoSocialFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "codigo_pais"
     */
    public function testPropertyCodigoPais()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "porte_fornecedor_id"
     */
    public function testPropertyPorteFornecedorId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantidade_homologada"
     */
    public function testPropertyQuantidadeHomologada()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_unitario_homologado"
     */
    public function testPropertyValorUnitarioHomologado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_total_homologado"
     */
    public function testPropertyValorTotalHomologado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "percentual_desconto"
     */
    public function testPropertyPercentualDesconto()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "indicador_subcontratacao"
     */
    public function testPropertyIndicadorSubcontratacao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ordem_classificacao_srp"
     */
    public function testPropertyOrdemClassificacaoSrp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_resultado"
     */
    public function testPropertyDataResultado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "motivo_cancelamento"
     */
    public function testPropertyMotivoCancelamento()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "porte_fornecedor_nome"
     */
    public function testPropertyPorteFornecedorNome()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "situacao_compra_item_resultado_nome"
     */
    public function testPropertySituacaoCompraItemResultadoNome()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sequencial_resultado"
     */
    public function testPropertySequencialResultado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "natureza_juridica_nome"
     */
    public function testPropertyNaturezaJuridicaNome()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "natureza_juridica_id"
     */
    public function testPropertyNaturezaJuridicaId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_controle_pncp_compra"
     */
    public function testPropertyNumeroControlePncpCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "situacao_compra_item_resultado_id"
     */
    public function testPropertySituacaoCompraItemResultadoId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
