<?php
/**
 * RecuperarTermoContratoDTOTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RecuperarTermoContratoDTOTest Class Doc Comment
 *
 * @category    Class
 * @description RecuperarTermoContratoDTO
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RecuperarTermoContratoDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RecuperarTermoContratoDTO"
     */
    public function testRecuperarTermoContratoDTO()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_fornecedor"
     */
    public function testPropertyQualificacaoFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_reajuste"
     */
    public function testPropertyQualificacaoReajuste()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "informativo_observacao"
     */
    public function testPropertyInformativoObservacao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_atualizacao"
     */
    public function testPropertyDataAtualizacao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fornecedor"
     */
    public function testPropertyFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ni_fornecedor"
     */
    public function testPropertyNiFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pessoa"
     */
    public function testPropertyTipoPessoa()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fornecedor_sub_contratado"
     */
    public function testPropertyFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pessoa_sub_contratada"
     */
    public function testPropertyTipoPessoaSubContratada()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sequencial_termo_contrato"
     */
    public function testPropertySequencialTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_inclusao"
     */
    public function testPropertyDataInclusao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_publicacao_pncp"
     */
    public function testPropertyDataPublicacaoPncp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fundamento_legal"
     */
    public function testPropertyFundamentoLegal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_acrescido"
     */
    public function testPropertyValorAcrescido()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "prazo_aditado_dias"
     */
    public function testPropertyPrazoAditadoDias()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_acrescimo_supressao"
     */
    public function testPropertyQualificacaoAcrescimoSupressao()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "qualificacao_vigencia"
     */
    public function testPropertyQualificacaoVigencia()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "orgao_entidade"
     */
    public function testPropertyOrgaoEntidade()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unidade"
     */
    public function testPropertyUnidade()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unidade_subrogada"
     */
    public function testPropertyUnidadeSubrogada()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_assinatura"
     */
    public function testPropertyDataAssinatura()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_vigencia_inicio"
     */
    public function testPropertyDataVigenciaInicio()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_vigencia_fim"
     */
    public function testPropertyDataVigenciaFim()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nome_razao_social_fornecedor"
     */
    public function testPropertyNomeRazaoSocialFornecedor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ni_fornecedor_sub_contratado"
     */
    public function testPropertyNiFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nome_fornecedor_sub_contratado"
     */
    public function testPropertyNomeFornecedorSubContratado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_termo_contrato"
     */
    public function testPropertyNumeroTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "informacao_complementar"
     */
    public function testPropertyInformacaoComplementar()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "processo"
     */
    public function testPropertyProcesso()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_parcelas"
     */
    public function testPropertyNumeroParcelas()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_parcela"
     */
    public function testPropertyValorParcela()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valor_global"
     */
    public function testPropertyValorGlobal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "orgao_subrogado"
     */
    public function testPropertyOrgaoSubrogado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objeto_termo_contrato"
     */
    public function testPropertyObjetoTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_termo_contrato_nome"
     */
    public function testPropertyTipoTermoContratoNome()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
