<?php
/**
 * ContrataoApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ContrataoApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContrataoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for consultarCompra
     *
     * Consultar Contratação.
     *
     */
    public function testConsultarCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for consultarCompra1
     *
     * Consultar Histórico de Contratação.
     *
     */
    public function testConsultarCompra1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for consultarQuantidade
     *
     * Consultar Quantidade Histórico de Contratação.
     *
     */
    public function testConsultarQuantidade()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImagem
     *
     * Recuperar Imagem de um Item de uma Contratação.
     *
     */
    public function testGetImagem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getImagemLista
     *
     * Recuperar Imagens de um Item de uma Contratação.
     *
     */
    public function testGetImagemLista()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for incluirCompra
     *
     * Inserir Contratação.
     *
     */
    public function testIncluirCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for incluirCompraItem
     *
     * Inserir Item de Contratação.
     *
     */
    public function testIncluirCompraItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for incluirCompraItemResultado
     *
     * Inserir Resultado de Item de Contratação.
     *
     */
    public function testIncluirCompraItemResultado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for inserirArquivo2
     *
     * Inserir Documento de Contratação.
     *
     */
    public function testInserirArquivo2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for inserirImagem
     *
     * Inserir Imagem de um Item de Contratação.
     *
     */
    public function testInserirImagem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pesquisarCompraItem
     *
     * Consultar Todos os Itens de Contratação.
     *
     */
    public function testPesquisarCompraItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarArquivo2
     *
     * Baixar Documento de Contratação.
     *
     */
    public function testRecuperarArquivo2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarCompraDocumentoQuantidade
     *
     * Consultar Quantidade de Documentos de Contratação.
     *
     */
    public function testRecuperarCompraDocumentoQuantidade()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarCompraItem
     *
     * Consultar Item de Contratação.
     *
     */
    public function testRecuperarCompraItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarCompraItemQuantidade
     *
     * Consultar Quantidade Item de Contratação.
     *
     */
    public function testRecuperarCompraItemQuantidade()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarInformacoesDocumentosCompra
     *
     * Consultar Documentos de Contratação.
     *
     */
    public function testRecuperarInformacoesDocumentosCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarResultado
     *
     * Consultar Resultado de Item de Contratação.
     *
     */
    public function testRecuperarResultado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarResultados
     *
     * Consultar Resultados de Item de Contratação.
     *
     */
    public function testRecuperarResultados()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removerCompra
     *
     * Excluir Contratação.
     *
     */
    public function testRemoverCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removerDocumentoCompra
     *
     * Excluir Documento de Contratação.
     *
     */
    public function testRemoverDocumentoCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removerImagem
     *
     * Remover Imagem de um Item de uma Contratação.
     *
     */
    public function testRemoverImagem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retificarCompra
     *
     * Retificar Contratação.
     *
     */
    public function testRetificarCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retificarCompraItem
     *
     * Retificar Item de Contratação.
     *
     */
    public function testRetificarCompraItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retificarCompraItemResultado
     *
     * Retificar Resultado de Item de Contratação.
     *
     */
    public function testRetificarCompraItemResultado()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retificarParcialmenteCompra
     *
     * Retificar parcialmente uma Contratação.
     *
     */
    public function testRetificarParcialmenteCompra()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retificarParcialmenteCompraItem
     *
     * Retificar Parcialmente um Item de Contratação.
     *
     */
    public function testRetificarParcialmenteCompraItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
