<?php
/**
 * TermoDeContratoApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API PNCP
 *
 * API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: css.serpro@serpro.gov.br
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TermoDeContratoApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TermoDeContratoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for inserirArquivo
     *
     * Inserir Documento de Termo de Contrato.
     *
     */
    public function testInserirArquivo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for inserirTermoContrato
     *
     * Inserir Termo de Contrato.
     *
     */
    public function testInserirTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarArquivo
     *
     * Baixar Documento de Termo de Contrato.
     *
     */
    public function testRecuperarArquivo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarInformacoesDocumentosTermoContrato
     *
     * Consultar Documentos de Termo de Contrato.
     *
     */
    public function testRecuperarInformacoesDocumentosTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarQuantidadeDocumentosTermoContrato
     *
     * Consultar Quantidade de Documentos de Termo de Contrato.
     *
     */
    public function testRecuperarQuantidadeDocumentosTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarQuantidadeTermosContrato
     *
     * Consultar Quantidade de Termos de Contrato.
     *
     */
    public function testRecuperarQuantidadeTermosContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarTermoContrato
     *
     * Consultar Termo de Contrato.
     *
     */
    public function testRecuperarTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recuperarTermosContrato
     *
     * Consultar Termos de Contrato.
     *
     */
    public function testRecuperarTermosContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removerContrato1
     *
     * Excluir Termo de Contrato.
     *
     */
    public function testRemoverContrato1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removerDocumentoContrato
     *
     * Excluir Documento de Termo de Contrato.
     *
     */
    public function testRemoverDocumentoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retificarTermoContrato
     *
     * Retificar Termo de Contrato.
     *
     */
    public function testRetificarTermoContrato()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
